### ISSUE TITLE
Safari's search input flashes on startup

### ISSUE THREAD

**Issue by Kronuz** [rs/SafariOmnibar#13]
Is there any way to make it so that the Safari's default "search" input doesn't flash when Safari is started? It briefly flashes before, I suppose, SaariOmnibar kicks in... but maybe there's a way to make SaariOmnibar start, or something, before that so it never is visible at any moment.

**Comment by rs** [comment]
I don't think so. I try to find a way to make the change sooner, but don't hold your breath :/
