### ISSUE TITLE
Problems with unicode (probably…)

### ISSUE THREAD

**Issue by ghost** [rs/SafariOmnibar#19]
There is a problem using special characters in some URLs, especially amazon.com/.de
(Compare: http://www.amazon.de/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=%20Hut&x=0&y=0 and http://www.amazon.de/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=%20Hüt&x=0&y=0)

**Comment by rs** [comment]
I guess Hut and Hüt aren't the same words in german, leading to different search result on amazon? What is the actual bug in SafariOmnibar?

**Comment by ghost** [comment]
Sorry, I should have explain the links in a bettet way.
The first link is a normal one (without any special character). The second one has an special character ("ü"), therefore Amazon should find articles which match to the string "Hüt" (I know, this two strings are different, but I need a string with a special character for this example). Amazon does not search articles matching to "Hüt" but to "HÃ". The string should be transformed to "H%FCt" to get results you were searching for.
I hope the problem is clear now.

**Comment by rs** [comment]
I think it's more an Amazon issue than encoding issue. Don't trust what Safari shows in the location bar, behind the hood, you Hüt query is encoded as H%C3%BCt which is the valid UTF-8 URI encoding for this string. You can try SafariOmnibar with other search services like google using the same query, you'll find that they work perfectly.

Note that H%FCt isn't a valid URI encoding.

**Comment by ghost** [comment]
You are right, it is an amazon issue. I downloaded Chrome and got there the same "error". I thought it its handleable because there existed an option in Keywurl to avoid this kind of "error" (I think it was named s.th. with UTF8).
Nevertheless, SafariOmnibar is a great plugin and is in use every day.

**Comment by rs** [comment]
Tanks for your comment. Could I close this issue though?

**Comment by ghost** [comment]
Yes, of course. Thanks for your patience and help.
