### ISSUE TITLE
Not working with Safari 5.0.6 (Developer Preview)

### ISSUE THREAD

**Issue by milkeush** [rs/SafariOmnibar#2]
My Mac is working with Mac OS X 10.5.8 (Leopard) and running the Developer Safari Preview (5.0.6) and when the install process is complete and I restarted Safari, but a popup tell me that :

http://cl.ly/8QKc

(If you can't fix that, someone can tell me how can I downgrade to Safari 5.0.5 (the last available on Apple.com) without losing my bookmarks, and other datas ?)

**Comment by rs** [comment]
The plugin may work but I didn't tested, it's why the plugin disabled.
Give me the number you have in Safari's About window (the number between parentheses after the version number). I will build a version for you to test if it works with this version.

**Comment by milkeush** [comment]
Oh okay, the number is 5533.22.2

**Comment by rs** [comment]
Fixed by last merge.
