### ISSUE TITLE
Using localhost in URL results in passing the URL to Google search

### ISSUE THREAD

**Issue by 0xDedSec42** [rs/SafariOmnibar#22]
I'm developing with Ruby on Rails. Since I installed the plugin, calling localhost:3000 (where the standard web server used by the Rails environment is running) results in passing this URL as a search string to Google. Using 127.0.0.1:3000 works fine.

**Comment by rs** [comment]
Please upgrade.

**Comment by 0xDedSec42** [comment]
Thanks. I hit a direct link in a blog post reviewing your plugin. Thanks for your work, works perfectly now.

**Comment by rs** [comment]
What was the blog so I can tell them to upgrade the link?

**Comment by 0xDedSec42** [comment]
http://www.thegraphicmac.com/save-space-search-with-google-from-safaris-url-bar
