### ISSUE TITLE
about URIs

### ISSUE THREAD

**Issue by parnmatt** [rs/SafariOmnibar#24]
The about URIs won't work …eg. about:blank
I know that all are accepted in Safari, though all about URI would return a blank page as Safari doesn't "use" them.

It's important for testing things cross browsers and cross platforms — i just don't want to disable and re-enable this SIMBL plugin each time.

**Comment by rs** [comment]
If someone knows which method to call to get the list of schemes safari handles itself, it would help for this issue.
