### ISSUE TITLE
google search changed

### ISSUE THREAD

**Issue by bjptwist** [rs/SafariOmnibar#27]
Hi. Great job. I'm just wondering if with the version 1.3 the feature of just typing the search term in the url bar and the a google search happens (like in chrome) is not available any more... Now, I can only preform a google search with the 'g' letter before my search. Is this a missing feature or just a decision you made?

**Comment by rs** [comment]
It's not a wanted behavior. Do you have a example of search that fail?

**Comment by bjptwist** [comment]
Anything I type in the url bar... This is not happening to you?

**Comment by bjptwist** [comment]
Sorry. I know what's the problem... The search with multiple words is ok. The problem is when I type just one word for search.

**Comment by bjptwist** [comment]
Sorry for closing this. My mistake.

**Comment by rs** [comment]
One word should search as well.

**Comment by bjptwist** [comment]
But is not searching in my case... 

If i type in the url bar: search, safari tries to open search.com

If i type in the url bar: search search, the search is done with google

**Comment by rs** [comment]
Do you have a domain search path in your DNS settings?
One word wont transform to search if the resolver return an IP for it. This can append if you have a search domain on a domain with a wildcard.

**Comment by bjptwist** [comment]
You are right. In fact i have a domain search imposed by my department network. But this doesn't happen with chrome. Can you add an option for consider searches with one word even with a domain search specified?

**Comment by rs** [comment]
Yes I will, and it will be disabled by default I think.

**Comment by bjptwist** [comment]
Thanks. Just 1 more idea, it would be great the possibility to export to a file (for example) the list of all created search keywords so that if I have to reinstall the os I can then import that list to safari again. Thanks. And keep the awesome job. Congrats.

**Comment by rs** [comment]
It's currently saved in you Safari preferences thus it will survive a reinstall if you keep your Safari prefs.

**Comment by bjptwist** [comment]
Can you tell me in which file precisely?

**Comment by rs** [comment]
~/Library/Preferences/com.apple.Safari.plist

**Comment by bjptwist** [comment]
Thanks.
