### ISSUE TITLE
file:// URLs directed to search

### ISSUE THREAD

**Issue by gbp** [rs/SafariOmnibar#28]
file:// URLs are inaccessible as they get treated like a search.  This is whether loaded from the bookmark or typed directly in to the omnibar

**Comment by rs** [comment]
Which version?

**Comment by gbp** [comment]
Latest version and compiled from source

**Comment by gbp** [comment]
I have fixed the issue locally - here is the pull request: https://github.com/rs/SafariOmnibar/pull/30
