### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by FredZ** [rs/SafariOmnibar#3]
Instructions for removal/uninstall are not correct:
No file SafariOmnibar.bundle  @ folder ~/Library/Application Support/SIMBL/Plugins/

Even worse: no folder ~/Library/Application Support/SIMBL/Plugins/ on my MacBook Pro

**Comment by FredZ** [comment]
Correction!

There IS a SIMBL folder containing SafariOmnibar.bundle :-)
The folder resides under Macintosh HD/Library/Application Support/ instead of under ~/Library/Application Support/

Problem solved :-)

**Comment by rs** [comment]
You're right, the file moved to /Library/...

**Comment by FredZ** [comment]
Thanks
