### ISSUE TITLE
Specify Google "I'm Feeling Lucky" search as a preference

### ISSUE THREAD

**Issue by jni** [rs/SafariOmnibar#31]
The original Omnibar arguably was the Firefox Awesome Bar. There, the search preference for non-URL inputs was a Google I'm Feeling Lucky search, which automatically takes you to the top hit in the Google search. In Chrome, it is easy to switch the Omnibar behavior to this by altering the default search engine. It would be useful if SafariOmnibar offered a similar preference.

**Comment by rs** [comment]
You can alter the default search engine in the search provider editor. With the last version of omnibar, right click in the location bar and select "Edit Omnibar Search Engines" menu item.

**Comment by jni** [comment]
Brilliant, fixed! Thanks for the pointer! =)
