### ISSUE TITLE
Beachballs sometimes

### ISSUE THREAD

**Issue by Gurpartap** [rs/SafariOmnibar#33]
I don't know when, but it beachballs for around 10 to 15 seconds sometimes when a new tab is opened.

OS X Snow Leopard with Safari 5.1.

Was this issue caught off already? (Since I installed from .pkg as of 5th August)

**Comment by rs** [comment]
HI,

I never heard about this issue. Are you using the last version of omnibar?

**Comment by Gurpartap** [comment]
Hi,

Yes, 1.3. I'll try reproducing it.

**Comment by Gurpartap** [comment]
Ok. I can't reproduce intentionally. What I could notice was, when it happens, it beachballs when return key is pressed. It beachballed right when I opened this issue page too. :)

(nothing very useful in the screenshots, just trying to be helpful)

http://cl.ly/343N3O44311A1V1A2P2S
http://cl.ly/1d0Z3b2A2I151p101o03

**Comment by chadrem** [comment]
I believe I can reproduce it consistently using Safari 5.1 on Lion:
1. Type a single word into the bar (example: can).
2. Hit enter.
3. Beach ball for a few seconds.
4. You will now see the google results for the search.

If I type multiple words into the bar separated by spaces (example: cnn food), then it will very quickly search google.  Single words without spaces seem to be the trick for reproducing the problem.

**Comment by rs** [comment]
Ok I guess I know why you get this. The last commit should fix this issue. If you know how to compile, please test, otherwise I can provide you with a beta version to confirm it fixes this issue.

**Comment by chadrem** [comment]
Thank you.  I compiled/installed the latest code and it definitely fixed the problem.

**Comment by Gurpartap** [comment]
Yes, definitely fixed. No more beachballs. Thanks.
