### ISSUE TITLE
PowerPC support

### ISSUE THREAD

**Issue by sideeffect42** [rs/SafariOmnibar#34]
A Universal Binary running on Leopard (Safari 5.0.6) would be great.

**Comment by milkeush** [comment]
Yes, the plugin still don't work with Safari 5.0.6 (and I'm PowerPC)

**Comment by rs** [comment]
If someone know how to add this with Xcode 4, tell me how and I'll add it.

**Comment by sideeffect42** [comment]
I don't know exactly how it works, but this link should help: http://stackoverflow.com/questions/5089491/creating-universal-binary-using-xcode-4-0

Or just use Xcode 3 ;-)

**Comment by rs** [comment]
"Xcode4 does not support PPC any longer. Officially you have to use Xcode3 to create binaries that contain code for Intel and PPC architectures. Xcode4 only supports two Mac architectures: Intel 32 bit and Intel 64 bit"

It's time to buy a new one guys :)

**Comment by sideeffect42** [comment]
Officially does not mean it's not possible ;-)
Why won't you just use Xcode 3 or apply this trick here: http://stackoverflow.com/questions/5333490/how-can-we-restore-ppc-ppc64-as-well-as-full-10-4-10-5-sdk-support-to-xcode-4?

"That's all folks. Considering how easy that was, you can imagine that Apple has certainly not dropped SDK 10.4/10.5 or ppc/ppc64 or GCC 4.0 support because this was a necessity, they dropped all that because they wanted to drop it."

Btw, I actually have a "newer one", but I never use it because it's slow and it just sucks.

Please think about it again ;-) Thank you.

**Comment by stefanschmidt** [comment]
Here is a quick port for PowerPCs running Safari 5.0.6 on Mac OS 10.5.8 (see the download section):

https://github.com/stefanschmidt/SafariOmnibar

Feedback welcome!

**Comment by sideeffect42** [comment]
Thank you sooo much for doing a port!

And the community showed that it's possible AGAIN!
You are the best!

**Comment by rs** [comment]
Added reference to your fork in the README. Thanks!
