### ISSUE TITLE
SafariOmnibar 1.3: Weird url parsing bug

### ISSUE THREAD

**Issue by jbergstroem** [rs/SafariOmnibar#36]
I haven't quite yet found the pattern, but this url will be googled when in address bar:
- http://aba.se/52559e83c1.png

This won't:
- http://abc.se/52559e83c1.png

… this will
- http://bza.se/abc

… this won't
-  http://cza.se/abc

Thoughts?

**Comment by rs** [comment]
aba.se and bza.se don't resolv to an IP, it's why omnibar fallback to google for them. I agree it shouldn't. The search query detection mechanism will be enhanced in future revisions.

**Comment by jbergstroem** [comment]
Sorry for using bogus names in my bug report. The issue was initially found with http://blä.se/52559e83c1.png , which indeed is a proper domain name.

**Comment by rs** [comment]
Ok the issue is with accented domain names.
