### ISSUE TITLE
Omnibar installation fails 

### ISSUE THREAD

**Issue by zizany** [rs/SafariOmnibar#37]
I've downloaded Omnibar for Safari 1.3 and run the installer. It gets through to the last step and then displays a message that says:

The installation failed.
The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.

I'm running OS 10.7. 
I've tried installing 1.1, 1.2, and 1.3. Safari was not running when I tried to install Omnibar. I've rebooted and fixed permissions.

Error log reads:
Aug  7 13:20:52 macintosh-10 installd[611]: PackageKit: ----- Begin install -----
Aug  7 13:20:52 macintosh-10 installd[611]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Safari Omnibar-1.3.pkg”." UserInfo=0x7f8332518f40 {NSFilePath=./postinstall, NSURL=file://localhost/Users/Old%20Mac/Downloads/Safari%20Omnibar-1.3.pkg#simbl.pkg, PKInstallPackageIdentifier=net.culater.SIMBL.pkg, NSLocalizedDescription=An error occurred while running scripts from the package “Safari Omnibar-1.3.pkg”.} {
        NSFilePath = "./postinstall";
        NSLocalizedDescription = "An error occurred while running scripts from the package \U201cSafari Omnibar-1.3.pkg\U201d.";
        NSURL = "file://localhost/Users/Old%20Mac/Downloads/Safari%20Omnibar-1.3.pkg#simbl.pkg";
        PKInstallPackageIdentifier = "net.culater.SIMBL.pkg";
    }
Aug  7 13:20:53 macintosh-10 Installer[598]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Aug  7 13:20:53 macintosh-10 Installer[598]: Displaying 'Install Failed' UI.
Aug  7 13:20:53 macintosh-10 Installer[598]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

Any ideas?

**Comment by rs** [comment]
Could you try to install SIMBL separately in order to see if it fails as well?

**Comment by zizany** [comment]
Same issue with SIMBL.

**Comment by zizany** [comment]
It appears, actually, to have installed correctly. Despite the error, it seems to be working with Safari. My old Google search bar has disappeared, my address bar has elongated, and I get the "GitHub, Inc." note on the far right. And, it seems to be working. Not sure what the issue is with the installation?

**Comment by rs** [comment]
Seems to be an error in the SIMBL post installation script.

**Comment by zizany** [comment]
OK. I guess I will just ignore it.

Thanks for the help!
