### ISSUE TITLE
Edit -> Find -> Google Search… to start new search with default search engine

### ISSUE THREAD

**Issue by brandonmartinez** [rs/SafariOmnibar#38]
Based off of Firefox and then Chrome, I had setup a shortcut to do a Google Search (cmd+k) in Safari. You can see it here: 

![Safari Shortcut Preview](https://img.skitch.com/20110808-agmsibjkrus7kg9ng6hnwwn4b.png)

It would be awesome if you followed a chrome-like approach, where if I hit cmd+k, it insert a _?_ or _Google:_ so that I can start a new search.

Thanks!

**Comment by jridgewell** [comment]
Try using ⌘l (lowercase L) to focus the omnibar, and then just type your search terms.

**Comment by brandonmartinez** [comment]
That doesn't work, because my ISP does DNS hijacking. I've used OpenDNS and Google DNS, but then I run into some issues with Netflix:

![Search Example](https://img.skitch.com/20110808-c2uy7wh5uqm1nehh7gda8fdqkw.png)

**Comment by rs** [comment]
Next rev will fix this last issue.
The main idea remain good, I keep it for the TODO

**Comment by brandonmartinez** [comment]
Woo! Thank you!
