### ISSUE TITLE
An option to hide the title bar?

### ISSUE THREAD

**Issue by henrymazza** [rs/SafariOmnibar#39]
And an option to use the location bar to show the title!

**Comment by rs** [comment]
Could you elaborate please?

**Comment by henrymazza** [comment]
I don't know if it's possible, so I'm practically messing with you! Today I use the location bar hidden ( ⌘ + shift + \ ), I like it that way. But my ultimate browser would show the title, and when you hover it the location bar would show up. So to it work it had to be a way to override the default title bar.

Anyway, really liked the package!

**Comment by rs** [comment]
If you do ⌘ + L you temporarily get the location bar, doesn't it fill your need?
It's certainly possible to implement what you want but I don't get the logic behind it. Would you use the hover on the title to show location in order to edit its content?

**Comment by henrymazza** [comment]
Yeah, you are right. Forget it! I had in mind this unified location/title bar so I didn't need to hide the location, but it's really useless!
