### ISSUE TITLE
allow me to keep the google search box, but have keyword searches in main address bar

### ISSUE THREAD

**Issue by plc** [rs/SafariOmnibar#43]
i love using keyword searches and find it equally slow if i have to prepend my google searches with "g" - might as well just press tab, but i love being able to type "imdb blah" or "wiki rah" and instantly go to the destination in the address bar.

**Comment by rs** [comment]
You don't have to prepend your search by g in order to search, by default any search in the location bar with no keyword will use the default search engine (google by default).

**Comment by plc** [comment]
ah, i find the autocomplete with my history too aggressive.
