### ISSUE TITLE
Can't use "&" in search terms

### ISSUE THREAD

**Issue by ghost** [rs/SafariOmnibar#45]
Typing e.g. "word1 & word2" only searches for "word1", while the rest gets ignored.

**Comment by jbergstroem** [comment]
This applies to most characters outside a-zA-Z0-9 such as `#€%&/(`

**Comment by rs** [comment]
Fixed

**Comment by rs** [comment]
Strange, github don't want me to close this issue...

**Comment by technoweenie** [comment]
You don't see a 'close issue' button?

**Comment by technoweenie** [comment]
Oh I see, you expected the 'fix' keyword to close the issue.  Until a few days ago, we had a bug that kept issues opened by deleted users from being updated.  So those commits weren't able to close the issue properly.
