### ISSUE TITLE
Extension install method

### ISSUE THREAD

**Issue by kalafalas** [rs/SafariOmnibar#47]
Its fine now - just a little old school, is there a particular reason is has to be a install package or can it be moved over to a "Safari extension"? normally i wouldn't care, but its nice to have them all in that little manager tab thingy, as well as automatic updates

**Comment by rs** [comment]
http://hackemist.com/SafariOmnibar/#faq

Why is this not a Safari extension?
Safari extensions are great to enhance sites or add toolbar buttons but are too restricted to modify Safari behaviors like Safari Omnibar does. To make Safari Omnibar possible, I've been forced to use something called "code injection" which is made easy by the SIMBL project.

**Comment by kalafalas** [comment]
Oh, cool, thanks :)
