### ISSUE TITLE
Mac OS X Lion: Omnibar won't load on restart with "reopen windows" enabled

### ISSUE THREAD

**Issue by bjarkekongstad** [rs/SafariOmnibar#5]
If "Reopen windows when logging back in" is enabled Omnibar will not load on restart in Safari windows that were open when the restart was performed.

Restarting Safari fixes it and loads the Omnibar just fine.

**Comment by rs** [comment]
Yep I got that too. I'll fix this in the next revision.

**Comment by rs** [comment]
Looks like a SIMBL issue. See http://code.google.com/p/simbl/issues/detail?id=52

**Comment by Gameunreal** [comment]
So, might this be fixed in OmniBar 1.3?

**Comment by rs** [comment]
It's not related to OmniBar but to SIMBL, the piece of software used by OmniBar to modify Safari. I try to help SIMBL author to fix the issue ASAP.

**Comment by nigelr** [comment]
awesome, found Ominibar yesterday... great work.. Came to report this bug and found you already had it in hand!

**Comment by kalafalas** [comment]
Restarting safari doesn't work for me, I _must_ do a log out and uncheck reopen windows when logging back in and then log back in and manually open safari to get it to work again - simply restarting safari after logging in normally doesn't work. This sucks because thats one of my favorite features of lion, nut i can't live without my omnibar! lol

**Comment by dustMason** [comment]
+1. I've taken to working around the issue by reinstalling OmniBar every time i restart. Not ideal!
OmniBar is awesome though.

**Comment by jerryen** [comment]
Do you guys have iTunes as a login item or reopened after a restart? That seems to delay the startup of some apps and SIMBL may be one of those which are delayed. If SIMBL isn't open, restarting Safari won't make it work. You'll have to wait until SIMBL is open or not have iTunes open at login before you restart Safari. It should work after that.

**Comment by dustMason** [comment]
I don't have iTunes as a login item and I still experience the issue when iTunes is not reopened after a restart.

**Comment by MrMicahPaz** [comment]
I have the same issue.

**Comment by kalafalas** [comment]
Same issue without iTunes (or iTunes helper) open at startup

**Comment by jmnwong** [comment]
Same issue.  But restarting (not re-installing) fixes it.

**Comment by s3w47m88** [comment]
Same issue but I just have to restart Safari and it's back.

**Comment by karlbright** [comment]
As mentioned earlier by rs. This is a SIMBL issue.

Just commenting to give future visitors some updated link to SIMBL issues.

[Issue 13](http://code.google.com/p/simbl/issues/detail?id=13) and [Issue 53](http://code.google.com/p/simbl/issues/detail?id=53)
