### ISSUE TITLE
that new feature in 1.5

### ISSUE THREAD

**Issue by fxjkhr** [rs/SafariOmnibar#51]
Yeah, you asked and I don't like it.

Not consistent/expected behavior for cmd+l

Don't touch established norms mang

**Comment by FentonBresler** [comment]
I on the other hand think this is a great idea, but it should only happen when pressing alt-cmd-F as if going to the standard web search box, and not cmd-L.

**Comment by rs** [comment]
I get that, next rev will only activate this on alt-cmd-f
