### ISSUE TITLE
Omnibar disappears after closing Safari

### ISSUE THREAD

**Issue by tllear** [rs/SafariOmnibar#55]
Hi, I have downloaded the Omnibar extension now three times to my Macbook Air, and each time I turn my computer off and then turn it back on the Omnibar disappears from Safari.  Is this a known problem?  Is there a fix for this?  I really enjoy the Omnibar and would appreciate any help you can give me.  Thanks a lot.

TL

**Comment by rs** [comment]
Please read the FAQ at http://hackemist.com/SafariOmnibar/#faq
