### ISSUE TITLE
Cant remove omnibar

### ISSUE THREAD

**Issue by papilov** [rs/SafariOmnibar#57]

**Comment by papilov** [comment]
because there is no directory in application support
10.7.1
http://i.imgur.com/xGGTE.png

**Comment by rs** [comment]
This is a screenshot of your home library directory. Safari Omnibar is in the root's library directory. Try Cmd+G in a finder window, and type "/Library/Application Support/SIMBL/" without the quotes.

**Comment by valgrinda** [comment]
I am using 10.7.2 and the location /Library/Application Support/SIMBL/ does not exist on my mac. Can you please comment on how to remove omnibar in that case?

**Comment by aslilac** [comment]
If that directory doesn't exist, it's not even there to remove.

**Comment by valgrinda** [comment]
sure, but the omnibar is still working in Safari. So omnibar is located somewhere. I would like to know where that location is.

**Comment by aslilac** [comment]
Try doing a spotlight search for "SafariOmnibar"

**Comment by valgrinda** [comment]
Spotlight does not find it. It must be located in a spot, which is not indexed by spotlight.
