### ISSUE TITLE
VNC / Core Screen Sharing

### ISSUE THREAD

**Issue by ttbakiatwoam** [rs/SafariOmnibar#58]
I recently found Omnibar and I find it very useful. However, I use the vnc features of OS X a lot and the simplest way the access them is to type VNC://youraddress in the address bar of a safari window. With Omnibar installed however that is not possible. It simply redirects me to a google search for that command. I believe this is a simple fix and I hope to see some resolution soon. I would hate to have to decide which feature I wanted more.

**Comment by philtr** [comment]
Looks like this is related to and would be fixed by #71.
