### ISSUE TITLE
Omnibar uninstalled after reboot

### ISSUE THREAD

**Issue by manufaktor** [rs/SafariOmnibar#59]
I've installed the Omnibar 1.5 PKG on 10.7.1 with Safari 5.1. Everything works fine until I reboot my Mac, then it's gone and I have to reinstall the whole thing.

It's strange, because the date of the SafariOmnibar.bundle file at /Library/Application Support/SIMBL/Plugins is the date I first installed Omnibar (which was like a couple of weeks ago).

**Comment by rs** [comment]
This is a known bug in SIMBL waiting for resolution. You can follow its resolution here: http://code.google.com/p/simbl/issues/detail?id=53

**Comment by rs** [comment]
In the meantime, just quite safari and relaunch it after reboot. This will fix it until next reboot.
