### ISSUE TITLE
Omnibar disappears on restart.

### ISSUE THREAD

**Issue by shantanugautam** [rs/SafariOmnibar#63]
The omnibar disappears after certain restarts of safari. I am not sure but i think it happens when you use the quit and discard option for safari. A normal restart fixes the problem.

**Comment by rs** [comment]
This is a known bug with SIMBL under Lion. The SIMBL author is aware of the issue and is working on a fix. In the meantime, you just have to restart Safari after reboot to get Omnibar to work again.

**Comment by shantanugautam** [comment]
Ok,thank you for the update.

**Comment by michaelaye** [comment]
@rs The Safari restart work-around does not work here (Lion, 10.7.3). What now? Reinstall?

**Comment by rs** [comment]
You may have installed an older version of SIMBL (via another plugin for instance). You can try to reinstall safari omnibar.

**Comment by michaelaye** [comment]
Well, i installed 1.6 that supposedly comes with a patched version of SIMBL. Or did you decide not to replace an existing one with the patched one?

**Comment by rs** [comment]
Please try installing SIMBL-0.9.9b-LionPatched.zip from here http://code.google.com/p/simbl/issues/detail?id=13
