### ISSUE TITLE
I'm feeling lucky

### ISSUE THREAD

**Issue by Gurpartap** [rs/SafariOmnibar#64]
Some keyword for Google's I'm feeling lucky? Like ? is for explicitly searching.

**Comment by rs** [comment]
I propose something like Option+Enter

**Comment by Gurpartap** [comment]
Option key is already occupied for downloading linked file when clicking or pressing enter from address bar. Command key for opening in new tab.

Shift+Enter seems to be available. (Shift+Left Click saves current page to Reading List)

**Comment by rs** [comment]
You're right, go for shift+enter then

**Comment by Gurpartap** [comment]
Could have been just adding ">" to the plist. But didn't like that it wasn't performing the same as "?" (had to press a space). These special symbol actions could ideally be better handled but meh. It works. :p

And getting in the way of keyDown seemed harder and unstructured, since there are multiple providers! :p

**Comment by Gurpartap** [comment]
Pull request here: https://github.com/rs/SafariOmnibar/pull/66

I wish Github had let me merge the pull request with this issue. Apologies for victimizing the issue queue with my attempt.
