### ISSUE TITLE
Bug when waking up from sleep

### ISSUE THREAD

**Issue by gferreroferri** [rs/SafariOmnibar#65]
Hi,
If I have Safari running and my laptop goes to sleep (I close it), when I start using it again and open a new Safari window, the google search bar appears again on the side!

**Comment by rs** [comment]
quite and restart safari, this is a known bug with lion.

**Comment by jbergstroem** [comment]
rs: I can relate to your frustration regarding this issue since it's not the first time its been reported. Perhaps it should be open with some "waiting for upstream"-tag so its easier for users to find it before creating a new one? (btw, issue 63 is the same thing)

**Comment by rs** [comment]
Yep, I'll do that. FYI, a patch for SIMBL fixing this issue have been submitted upstream several weeks ago with no answer from the author :/
