### ISSUE TITLE
default Safari address and search bar come back after a while

### ISSUE THREAD

**Issue by aknewhope** [rs/SafariOmnibar#75]
I leave my computer on for weeks at a time, because I always have at least 6 Safari tabs open and can't just shut down. I come back and wake my computer from sleep, and the omnibar is gone, and Safari's default address and search bar is back. If I restart Safari it comes back. The file is still in internet plugins. Any suggestions?

**Comment by jbergstroem** [comment]
Is it perhaps so that you logged in/out and had that checkbox called "reopen windows when logging back in" ticked?

**Comment by aknewhope** [comment]
No. I put the computer to sleep and when I wake it, the omnibar has gone away. I then have to restart safari to bring it back.

**Comment by aknewhope** [comment]
Right now I have Safari open and the Omnibar is not loaded. I see the default Safari address+search boxes.

**Comment by jbergstroem** [comment]
This is most likely an issue with SIMBL. There is a confirmed problem related to logging in/out with the checkbox I mentioned ticked which gives the exact same result.

**Comment by ratberryjam** [comment]
This is a duplicate of [#65](https://github.com/rs/SafariOmnibar/issues/65).

**Comment by rs** [comment]
Please reinstall using the latest installer. It's bundled with a patch version of SIMBL which fix this issue.
