### ISSUE TITLE
Omnibar Not Showing After Lion Resume

### ISSUE THREAD

**Issue by 552Industries** [rs/SafariOmnibar#77]
If I leave the Safari application open and then restart or login, the omnibus does not appear. Instead, it shows the standard Safari dual address/search toolbar.

**Comment by pcasaretto** [comment]
Duplicate of #65 ?

**Comment by 552Industries** [comment]
If #65 is related to Lion and resume, then yes. Where is the author's response of this issue?

**Comment by jbergstroem** [comment]
The authors stance is that this is an upstream bug, which means that there isn't much to do until SIMBL fixes this – see http://code.google.com/p/simbl/issues/detail?id=52 for more info

**Comment by rs** [comment]
Please reinstall from the latest installer. It's bundled with a patch SIMBL version that fix this issue.

**Comment by 552Industries** [comment]
No dice. I installed the latest version and yet the issue still occurs.

EDIT:  My OS is 10.7.2 like the majority of Mac users.
