### ISSUE TITLE
Localhost redirects to search

### ISSUE THREAD

**Issue by IanMitchell** [rs/SafariOmnibar#8]
When I enter "localhost:3000" as a url, safari will redirect to a google search. 127.0.0.1:3000 works, but it would be nice to have the convenience of localhost. After uninstalling your plugin, Safari did revert to recognizing localhost, so I'm fairly certain it's just not a recognized valid url in your plugin. Hopefully it's an easy fix! Cheers mate.

**Comment by rs** [comment]
Please upgrade to 1.2
