### ISSUE TITLE
SafariOmnibar Still not Loading after Lion Resume (v1.6)

### ISSUE THREAD

**Issue by 552Industries** [rs/SafariOmnibar#80]
Same as #65, but the updated version of SafariOmnibar is still not fixing the problem with the SIMBL injection on startup.

**Comment by rs** [comment]
Did you reinstalled the package from scratch and rebooted you mac?

**Comment by 552Industries** [comment]
Nevermind, I fixed the issue myself. Apparently, your latest version of SafariOmnibar with the included patch of SIMBL didn't overwrite one of the files.

Fix instructions: 

Download and run the SIMBL 0.9.9 Lion patch. (http://code.google.com/p/simbl/issues/detail?id=13#c19 Comment 14.)
Stop SIMBL Agent via Activity Monitor
Replace SIMBL.osax in /Library/ScriptingAdditions (Download from SIMBL patch url above.)
Completely reboot. (Don't just log in/out.)

Result? Profit.
