### ISSUE TITLE
Can't remove this plugin at all.

### ISSUE THREAD

**Issue by ibock** [rs/SafariOmnibar#90]
I have the Mountain Lion DP2 and I literally cannot remove this plugin, and _every_ single time I open Safari I get told that Omnibar isn't going to load, but I get an annoying pop-up saying it. I ran the uninstaller and I got an error after trying to run it. It said "error moving to trash".

I just want this thing off my computer. Is there any way to do that?

**Comment by rs** [comment]
Please run the following command:

```
$ sudo rm -rf /Library/Application\ Support/SIMBL/Plugins/SafariTabSwitching.bundle
```

**Comment by ibock** [comment]
Thank you so much! You just saved me a lot of frustration.

**Comment by rs** [comment]
You're welcome
