### ISSUE TITLE
Continue Search Engine Editing Piece

### ISSUE THREAD

**Issue by ghost** [rs/SafariOmnibar#92]
I just installed mountain lion and I'm instantly missing this in safari 6.0 for the search engine editing piece.  Just wondering if you could continue that piece in a version that would be supported in 6.0 because it's very useful.

**Comment by rs** [comment]
I don't have the time to port this feature to Safari 6.0 for the moment but it's definitely a feature I miss as well.

**Comment by ghost** [comment]
word.  well if you find the time in the future, i, and I'm sure many others, will find the $ the donate.
