### ISSUE TITLE
 Safari 6 - as a precaution it has not been loaded into Safari

### ISSUE THREAD

**Issue by loop** [rs/SafariOmnibar#93]
On Safari 6 this error pops up when launching Safari:

![Error](http://f.cl.ly/items/0d1m2h2T0h2N1y2C2M3K/Screen%20Shot%202012-07-25%20at%2003.52.00.png)

I understand that by default it is now an Omnibar so I am trying to uninstall this extension but I cannot find it in the Extensions menu and nor are the files present in the Extensions folder in Finder.

Is there a way to uninstall it that I can't find?

**Comment by loop** [comment]
Found a fix:

Delete ~/Library/Application Support/SIMBL/SafariOmnibar.bundle

**Comment by rs** [comment]
I uploaded a script to do just that for you: https://github.com/downloads/rs/SafariOmnibar/uninstall.command.zip

**Comment by disinfeqt** [comment]
Same thing happens to Tab Switching, I can't live without it.

Edit: Sorry, I just updated it. Now works great.

Thank you.
